apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      env: production
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: myweb-pod
      labels:
        env: production
    spec:
      containers:
      - name: myweb-con
        image: userprashant/dynamic-master-slave:latest
